version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork: