// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package v1 // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Activity struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time                 *MyTimestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_b43d8e0c80fe242b, []int{0}
}
func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (dst *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(dst, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Activity) GetTime() *MyTimestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Activity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MyTimestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyTimestamp) Reset()         { *m = MyTimestamp{} }
func (m *MyTimestamp) String() string { return proto.CompactTextString(m) }
func (*MyTimestamp) ProtoMessage()    {}
func (*MyTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_b43d8e0c80fe242b, []int{1}
}
func (m *MyTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyTimestamp.Unmarshal(m, b)
}
func (m *MyTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyTimestamp.Marshal(b, m, deterministic)
}
func (dst *MyTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyTimestamp.Merge(dst, src)
}
func (m *MyTimestamp) XXX_Size() int {
	return xxx_messageInfo_MyTimestamp.Size(m)
}
func (m *MyTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_MyTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_MyTimestamp proto.InternalMessageInfo

func (m *MyTimestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *MyTimestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

func init() {
	proto.RegisterType((*Activity)(nil), "api.v1.Activity")
	proto.RegisterType((*MyTimestamp)(nil), "api.v1.MyTimestamp")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_b43d8e0c80fe242b) }

var fileDescriptor_server_b43d8e0c80fe242b = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x3f, 0xab, 0xc2, 0x30,
	0x14, 0x47, 0x49, 0xff, 0xbd, 0xf7, 0x6e, 0x1f, 0x0e, 0xd1, 0x21, 0x63, 0xe8, 0x62, 0xa7, 0x40,
	0x75, 0x14, 0x07, 0xdd, 0x5d, 0x82, 0x93, 0x5b, 0x6d, 0x32, 0xdc, 0xa1, 0x49, 0x48, 0x42, 0xa0,
	0xdf, 0x5e, 0x48, 0x11, 0x3a, 0x9e, 0xcb, 0x3d, 0x9c, 0x1f, 0xfc, 0x07, 0xed, 0x93, 0xf6, 0xc2,
	0x79, 0x1b, 0x2d, 0x6d, 0x46, 0x87, 0x22, 0x0d, 0x9d, 0x86, 0xdf, 0xdb, 0x14, 0x31, 0x61, 0x5c,
	0xe8, 0x0e, 0x0a, 0x54, 0x8c, 0x70, 0xd2, 0xd7, 0xb2, 0x40, 0x45, 0x8f, 0x50, 0x45, 0x9c, 0x35,
	0x2b, 0x38, 0xe9, 0xdb, 0xd3, 0x5e, 0xac, 0x8a, 0x78, 0x2c, 0x4f, 0x9c, 0x75, 0x88, 0xe3, 0xec,
	0x64, 0x7e, 0xa0, 0x1c, 0x5a, 0xa5, 0xc3, 0xe4, 0xd1, 0x45, 0xb4, 0x86, 0x95, 0x9c, 0xf4, 0x7f,
	0x72, 0x7b, 0xea, 0xae, 0xd0, 0x6e, 0x34, 0xca, 0xe0, 0x27, 0xe8, 0xc9, 0x1a, 0x15, 0x72, 0xae,
	0x94, 0x5f, 0xa4, 0x07, 0xa8, 0xcd, 0x68, 0x6c, 0xc8, 0xd1, 0x5a, 0xae, 0x70, 0x6f, 0x5e, 0x95,
	0xb8, 0xa4, 0xe1, 0xdd, 0xe4, 0xf1, 0xe7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x32, 0x3c,
	0x92, 0xcc, 0x00, 0x00, 0x00,
}
