version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  addbook:
    build:
      context: ./addbooks
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./addbooks/logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    networks:
      - mynetwork

  grpc:
    build:
      context: ./servergrpc
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    volumes:
      - ./servergrpc/logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - addbook
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork: